config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :docs
  get 'welcome/index'

root 'docs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    has_many :favorites, dependent: :destroy

    scope :favorited_by, -> (email) { joins(:favorites).where(favorites: { user: User.where(email: email) }) }


  def self.search(search)
    where("name ILIKE ? OR specialty ILIKE ?", "%#{search.downcase}%", "%#{search.downcase}%")
  end



end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :doc, counter_cache: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, omniauth_providers: [:facebook]

   #find the user by ID and Email
  def self.find(user_key)
    if user_key.to_s.include? '@'
      return User.find_by(email: user_key)
    else
      return super user_key
    end
  end

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.provider = auth.provider
    user.uid = auth.uid
    user.password = Devise.friendly_token[0,20]
  end
end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(:username, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :current_password)}


  end

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update]
  helper_method :sort_column


  def index
      # i set @docs let it be the complete list of doctors in the main page
    @docs = Doc.all
    if params[:search]
       @docs = Doc.search(params[:search])
     else
       @docs = Doc.all
       @docs = Doc.order(sort_column + " " + sort_direction)
     end
  end


  def show
        # i set @docs let it be the complete list of doctors in the show page
      @docs = Doc.all
          #this line will order each time we click on the title of the tab
      @docs = Doc.order(sort_column + " " + sort_direction)
  end

  def new
    @doc = Doc.new
  end


  def edit
  end

  def create
  end


  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      # i set up @doc to be the one selected
      @doc = Doc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doc_params
      params.require(:doc).permit(:name, :specialty, :zip, :review)
    end

# when we lunch the front page it will sort by speciality automaticly
    def sort_column
      params[:sort] || 'specialty'
    end
    # when we lunch the front page it will be an asc sort automaticly

    def sort_direction
      params[:direction] || "asc"
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user! 
  before_action :find_doc!

  private

  def find_doc!
    @doc = Doc.find_by_slug!(params[:doc_slug])
  end

    def create
    current_user.favorite(@doc)

    render 'docs/show'
  end

  def destroy
    current_user.unfavorite(@doc)

    render 'docs/show'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def initialize
    end
    
  def index
  end

  def doc
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

# This methode allow me to sort my list when i will click on it
  def sortable (column, title = nil)
    title ||= column.titleize
    # we check if the column match the sort column and if the direction is asc then we do desc if not we do asc
    direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, :sort => column , :direction => direction

end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= form_with(model: doc, local: true) do |form| %>
  <% if doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% doc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :doc_name %>
  </div>

  <div class="field">
    <%= form.label :specialty %>
    <%= form.text_field :specialty, id: :doc_specialty %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :doc_zip %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_field :review, id: :doc_review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing Doc</h1>

<%= render 'form', doc: @doc %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Doctors in your Area</h1></center>
<center><h4>Search by Name or Specialty</h4></center>
<br>
<center>
  <!-- Search bar is working on local but not on heroku -->

<%= form_tag(docs_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Doctors" %>
    <%= submit_tag "Search", :name => nil %>
    <% if @docs.blank? %>
  <h4>There are no doctors containing the term <%= params[:search] %>.</h4>
<% end %>
<% end %>
</center>
<br>

  <table class="table">
  <thead>
    <tr>
      <th><%= sortable "Name"%></th>
      <th><%= sortable "Specialty"%></th>
      <th><%= sortable 'Zip', 'Zip Code' %></th>
      <th><%= sortable 'review' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="listdoc">
    <!-- I will print the list of all the doctor -->
    <% @docs.each do |doc| %>

      <tr  class="clickable" onclick="location.href='<%= doc_path(doc) %>'">
        <td><%= doc.name %></td>
        <td><%= doc.specialty %></td>
        <td><%= doc.zip %></td>
        <td><%= doc.review %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>
<p> To add a new doctor please contact us </p>

app/views/docs/new.html.erb
<h1>New Doc</h1>

<%= render 'form', doc: @doc %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>
<center><h1> <%= @doc.name %> </h1>
<p>
  <strong>Name:</strong>
  <%= @doc.name %>
</p>

<p>
  <strong>Specialty:</strong>
  <%= @doc.specialty %>
</p>

<p>
  <strong>Zip Code:</strong>
  <%= @doc.zip %>
</p>

<p>
  <strong>Review:</strong>
  <%= @doc.review %>/10
</p>
<br>
</center>
 <!-- this line will change each time the speciality is different -->
  <p><b>Other <%= @doc.specialty %> Doctors:</b></p>

  <table class="table">
    <thead>
      <tr>
        <th><%= sortable 'Name'%></th>
        <th><%= sortable  'Specialty' %></th>
        <th><%= sortable  'Zip', 'Zip Code'  %></th>
        <th><%= sortable  'Review'  %></th>
        <th colspan="4"></th>
        
      </tr>
    </thead>

        <tbody class="listdoc">
       <!-- I am doing a loop for search in all the doctors list -->
<% @docs.each do |doc| %>
<!-- then i select only the doctors with the same speciality than the one display on this page-->
<% if doc.specialty == @doc.specialty %>
    <tr  class="clickable" onclick="location.href='<%= doc_path(doc) %>'">
        <td><%= link_to doc.name, doc%></td>
        <td><%= doc.specialty %></td>
        <td><%= doc.zip%></td>
        <td><%= doc.review%></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', docs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocListing</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">DocListing</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
   
            <p class="navbar-text pull-right">
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
 </div>
  </nav>
    <div>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome to Doc Listing</h1>
<p>Find me in app/views/welcome/index.html.erb</p>